version: "3.8"

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stock_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
